// TODO: Update the data
export const courses = [
  "BTech",
  "MSc(Int)",
  "MSc(2 yr)",
  "MTech",
  "PhD",
  "MT(Dual)",
  "MSc-PhD(Dual)",
  "MBA",
  "MDes",
  "BS",
  "MS-Research",
  "BT-MS",
  "BS-MS",
  "BS-MT",
  "BT-MBA",
  "BS-MBA",
  "BT-M.Des",
  "BS-M.Des",
  "MTech-PhD",
  "PhD-M.Des",
  "PhD-MS(Research)",
];
export const departments = [
  "AE",
  "CHE",
  "CE",
  "CSE",
  "EE",
  "IME",
  "ME",
  "MSE",
  "CHM",
  "MATH",
  "PHY",
  "ECO",
  "PSE",
  "EEM",
  "BSBE",
  "DES",
  "ES",
  "NET",
  "MSP",
  "CGS",
  "HSS",
  "MTH",
  "STAT",
  "MTSC",
  "OTH",
  "SEE",
  "SDS",
  "SSA",
  "SCU",
  "PREP",
  "MDES",
  "DOMS",
  "SPAS",
  "C3IH",
  "KSS",
  "DIS",
];

export const departmentNameMap = {
  "Aerospace Engineering": "AE",
  "Biological Sciences and Bioengineering": "BSBE",
  "Chemical Engineering": "CHE",
  "Chemistry": "CHM",
  "Civil Engineering": "CE",
  "Cognitive Science": "CGS",
  "Computer Science and Engineering": "CSE",
  "Design": "DES",
  "Earth Science": "ES",
  "Economics": "ECO",
  "Electrical Engineering": "EE",
  "Environmental Engineering and Management": "EEM",
  "Humanities and Social Sciences": "HSS",
  "Industrial and Management Engineering": "IME",
  "Laser Technology": "OTH",
  "Materials Science Programme": "MSP",
  "Materials Science and Engineering": "MSE",
  "Mathematics": "MTH",
  "Mathematics and Scientific Computing": "MTSC",
  "Mathematics and Statistics": "MTST",
  "Mechanical Engineering": "ME",
  "Nuclear Engineering and Technology Programme": "NET",
  "Photonics Science and Engineering": "PSE",
  "Physics": "PHY",
  "Space Science and Astronomy": "SSA",
  "Space, Planetary and Astronomical Sciences and Engineering": "SPAS",
  "Statistics": "STAT",
  "Statistics and Data Science": "SDS",
  "Sustainable Energy Engineering": "SEE"
};
export const halls = [
  "HALL1",
  "HALL2",
  "HALL3",
  "HALL4",
  "HALL5",
  "HALL6",
  "HALL7",
  "HALL8",
  "HALL9",
  "HALLX",
  "HALLXI",
  "HALL12",
  "HALL13",
  "HALL14",
  "GH",
  "DAY",
  "ACES",
  "CPWD",
  "RA",
  "NRA",
  "SBRA",
  "TYPE1",
  "TYPE1B",
  "TYPE5"

];
